apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: manage-list-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: manage-list-container
            image: abdelgadirkamal/manage-list-app:latest
            env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: GIT_REPO_URL
              value: "https://github.com/AbdelgadirKamal/testing.git"
            - name: GIT_REPO_PATH
              value: "/var/blacklist"
            - name: GIT_BLACKLIST_FILE
              value: "/var/blacklist/blacklist.yaml"
            - name: MEMCACHED_TIMEOUT
              value: "60"
            - name: MEMCACHED_SERVICE
              value: "memcached"
            - name: MEMCACHED_SERVICE_PORT
              value: "11211"
            - name: TZ
              value: "Australia/Sydney"
          restartPolicy: OnFailure
